name: "Unpublished"
description: "Does your package need to be published?"
inputs:
  cwd:
    description: "The directory your package lives in"
    required: false
    default: "."
outputs:
  version:
    description: "Your current package version"
  is-unpublished:
    description: "Is your package unpublished?"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.cwd }}
