name: is-unpublished
description: "Does your package need to be published?"
inputs:
  cwd:
    description: "The directory your package lives in"
    required: false
    default: "."
outputs:
  name:
    description: "Your package name"
  version:
    description: "Your package version"
  is-unpublished:
    description: "Is your package unpublished?"
runs:
  using: "node12"
  main: ".github/dist/index.js"
