name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
          node-version: 12.x
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - uses: actions/setup-elixir@v1
        with:
          otp-version: 22.2
          elixir-version: 1.10.1
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Test
        run: yarn test --ci --coverage
      - name: Publish
        if: github.ref == "refs/heads/master"
        run: |
          if yarn run -s is-unpublished; then
            yarn publish --access public
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
